# Generated by Django 4.1 on 2023-12-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程号",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("time", models.CharField(max_length=30, verbose_name="上课时间")),
                ("location", models.CharField(max_length=30, verbose_name="上课地点")),
                ("year", models.IntegerField(default=2023, verbose_name="年份")),
                ("semester", models.IntegerField(default=1, verbose_name="学期")),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学号",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="工号",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师",
                "db_table": "teachers",
            },
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField(null=True, verbose_name="成绩")),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.course"
                    ),
                ),
                (
                    "s_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
            ],
            options={
                "db_table": "student_course",
                "unique_together": {("s_id", "c_id")},
            },
        ),
    ]
